import type { NextPage } from 'next'
import Head from 'next/head'
import Lottie from 'lottie-react';
import lot3 from '../public/lottie/lot3.json';
import lot4 from '../public/lottie/lot4.json';
import styles from '../styles/Home.module.scss'
import ThreeJS from '../public/script/Lib/three';
// import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>준비중</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ThreeJS />
      </main>
    </div>
  )
}

export default Home
