import type { NextPage } from 'next'
import Head from 'next/head'
import Lottie from 'lottie-react';
import lot1 from '../public/lottie/lot1.json';
// import Image from 'next/image'
import Script from 'next/script';
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>준비중</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script
          src=""
          strategy="lazyOnload"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.visual}>
          <Lottie animationData={lot1}></Lottie>
        </div>
      </main>
    </div>
  )
}

export default Home
